version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/node:10.16.3
      - image: circleci/mongo:4.1
    steps:
      - checkout
      - restore_cache:
            keys:
              - v1-dependencies-{{ checksum "package.json" }}
              - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: node test.js